name: silebezi
favicon: null
layout_spectrum: 0.25589891616255045
typography_spectrum: 0.9610829770099372
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
  brandStrength: 0.7916883716825396
  lightness: 0.7647281191311777
  saturation: 0.035762586863711476
  rhythmicContrast: 0.49751756992191076
purpose: []
